/* Generated by scripts/sync-catalog.mjs. Do not edit.

   What the appautomaton org contained at the last build, and what each project's
   address answered when it was asked. Committed so the diff shows when a
   project's description changed or a page went live, and so the site still
   builds with no network. Run `npm run sync` to refresh. */

export type OrgRepo = {
  /** Durable GitHub identity. Display order never comes from the API response. */
  repoId: number
  createdAt: string
  catalogOrder: number
  name: string
  /** The repository's own one-liner, as GitHub reports it. */
  description: string
  topics: string[]
  /** Canonical website from the repository About field. */
  homepage: string
  /** Fallback category for newly published sites without editorial placement. */
  automaticGroup?: string
  /** True when https://appautomaton.com/<name>/ answered 200. */
  hasSite: boolean
  /** The date that page was last built, from its Last-Modified header. */
  lastmod: string | null
  /** The project's own sitemap, when it serves one. */
  sitemap: string | null
}

export const org = "appautomaton"
export const origin = "https://appautomaton.com"

export const repos: OrgRepo[] = [
  {
    "repoId": 1119857172,
    "createdAt": "2025-12-20T01:26:41Z",
    "catalogOrder": 0,
    "name": "agent-designer",
    "description": "Portable SKILLs workspace for Claude Code, Codex, and Gemini — issue-driven workflows and cross-agent collaboration via bridge scripts with session continuity.",
    "topics": [
      "agent-skills",
      "agentic-workflows",
      "ai-agents",
      "ai-coding-assistant",
      "claude-code",
      "claude-skills",
      "codex",
      "gemini-cli",
      "mcp"
    ],
    "homepage": "https://appautomaton.com/agent-designer/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/agent-designer/sitemap.xml"
  },
  {
    "repoId": 1226150677,
    "createdAt": "2026-05-01T03:08:30Z",
    "catalogOrder": 7,
    "name": "automaton",
    "description": "AI coding agent framework — portable, stage-gated harness for Claude Code, Codex, and OpenCode",
    "topics": [
      "agent-harness",
      "agentic-workflow",
      "ai-agents",
      "claude-code",
      "codex",
      "developer-tools",
      "llm",
      "opencode"
    ],
    "homepage": "https://appautomaton.com/automaton/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/automaton/sitemap.xml"
  },
  {
    "repoId": 1282632918,
    "createdAt": "2026-06-28T02:57:38Z",
    "catalogOrder": 10,
    "name": "docker-for-apple-container",
    "description": "Run docker and docker compose on macOS, backed by Apple's native container CLI. No Docker Desktop.",
    "topics": [
      "apple-container",
      "apple-silicon",
      "container-cli",
      "containers",
      "docker",
      "docker-cli-shim",
      "docker-compose",
      "docker-desktop-alternative",
      "docker-shim",
      "macos"
    ],
    "homepage": "https://appautomaton.com/docker-for-apple-container/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/docker-for-apple-container/sitemap.xml"
  },
  {
    "repoId": 1140927126,
    "createdAt": "2026-01-24T00:06:34Z",
    "catalogOrder": 1,
    "name": "document-SKILLs",
    "description": "Claude Code and Codex SKILLs for PDF, Excel, Word, and PowerPoint manipulation — extraction, forms, formulas, tracked changes, adapted from Anthropic skills.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "claude-skills",
      "codex",
      "document-processing",
      "docx",
      "excel",
      "pdf-extraction",
      "pptx"
    ],
    "homepage": "https://appautomaton.com/document-SKILLs/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/document-SKILLs/sitemap.xml"
  },
  {
    "repoId": 950805672,
    "createdAt": "2025-03-18T17:58:07Z",
    "catalogOrder": 5,
    "name": "latex-arxiv-SKILL",
    "description": "A highly customizable agentic harness for arXiv-ready ML/AI review papers (and beyond). It drives agentic AI like Codex CLI and Claude Code through a gated LaTeX workflow with verified BibTeX citations.",
    "topics": [
      "academic-writing",
      "agent-skill",
      "agentic",
      "agentic-ai",
      "ai-agents",
      "anthropic",
      "arxiv",
      "bibtex",
      "citations",
      "claude-code",
      "codex",
      "ieeetran",
      "latex",
      "literature-review",
      "llm",
      "openai",
      "paper-generation",
      "research-paper",
      "review-paper",
      "scientific-writing"
    ],
    "homepage": "https://appautomaton.com/latex-arxiv-SKILL/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/latex-arxiv-SKILL/sitemap.xml"
  },
  {
    "repoId": 1181193024,
    "createdAt": "2026-03-13T21:11:43Z",
    "catalogOrder": 14,
    "name": "ltx-video-mlx",
    "description": "LTX-2.3 22B text-to-video and image-to-video generation with synchronized audio on Apple Silicon — 8-bit/4-bit MLX inference plus on-device LoRA fine-tuning.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "diffusion-models",
      "image-to-video",
      "lora",
      "mlx",
      "on-device-ai",
      "text-to-video",
      "video-generation"
    ],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  },
  {
    "repoId": 1204977925,
    "createdAt": "2026-04-08T14:13:33Z",
    "catalogOrder": 9,
    "name": "markmaton",
    "description": "Lightweight HTML-to-Markdown parser for AI agent workflows — Python CLI and API around a fast Go engine, available on PyPI.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "cli-tool",
      "content-extraction",
      "firecrawl",
      "golang",
      "html-parser",
      "html-to-markdown",
      "html2md",
      "llm",
      "markdown",
      "markdown-converter",
      "pypi",
      "python",
      "rag",
      "web-scraping"
    ],
    "homepage": "https://appautomaton.com/markmaton/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/markmaton/sitemap.xml"
  },
  {
    "repoId": 1239193367,
    "createdAt": "2026-05-14T21:19:16Z",
    "catalogOrder": 17,
    "name": "mlx-atomistic",
    "description": "Apple Silicon-native molecular dynamics and DFT runtime built on MLX and Metal — the GPU on your Mac, no CUDA or cloud.",
    "topics": [
      "apple-silicon",
      "atomistic-simulation",
      "computational-chemistry",
      "density-functional-theory",
      "dft",
      "gpu",
      "materials-science",
      "metal",
      "mlx",
      "molecular-dynamics",
      "molecular-simulation",
      "python",
      "scientific-computing"
    ],
    "homepage": "https://appautomaton.com/mlx-atomistic/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/mlx-atomistic/sitemap-index.xml"
  },
  {
    "repoId": 1260752036,
    "createdAt": "2026-06-05T20:45:31Z",
    "catalogOrder": 15,
    "name": "mlx-cv",
    "description": "MLX-native computer vision for Apple Silicon: open-vocabulary grounding, object detection, depth and camera geometry, segmentation, and video object tracking.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "computer-vision",
      "depth-estimation",
      "image-segmentation",
      "macos",
      "mlx",
      "object-detection",
      "object-tracking",
      "on-device-ai",
      "open-vocabulary-detection",
      "panoptic-segmentation",
      "python",
      "sam3",
      "segment-anything",
      "visual-grounding"
    ],
    "homepage": "https://appautomaton.com/mlx-cv/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/mlx-cv/sitemap.xml"
  },
  {
    "repoId": 1323419458,
    "createdAt": "2026-08-04T22:15:04Z",
    "catalogOrder": 19,
    "name": "mlx-h3",
    "description": "Pure MLX MiniMax-H3 text-to-video-and-audio inference for Apple Silicon.",
    "topics": [
      "apple-silicon",
      "audio-generation",
      "generative-ai",
      "macos",
      "minimax-h3",
      "mlx",
      "text-to-video",
      "video-generation"
    ],
    "homepage": "https://appautomaton.com/mlx-h3/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/mlx-h3/sitemap.xml"
  },
  {
    "repoId": 1334345932,
    "createdAt": "2026-08-14T15:57:29Z",
    "catalogOrder": 18,
    "name": "mlx-minimax-music3",
    "description": "Pure MLX inference for MiniMax Music 3 on Apple silicon.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "audio-generation",
      "flow-matching",
      "generative-ai",
      "macos",
      "minimax-music",
      "mlx",
      "music-generation",
      "on-device-ai",
      "text-to-music"
    ],
    "homepage": "https://appautomaton.com/mlx-minimax-music3/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/mlx-minimax-music3/sitemap.xml"
  },
  {
    "repoId": 1227277248,
    "createdAt": "2026-05-02T13:09:20Z",
    "catalogOrder": 16,
    "name": "mlx-spatial",
    "description": "MLX-native 3D and spatial inference for Apple silicon: object reconstruction, image-to-mesh, scene geometry, Gaussian splats, and multi-view bundles.",
    "topics": [
      "3d-generation",
      "3d-reconstruction",
      "apple-silicon",
      "gaussian-splatting",
      "image-to-3d",
      "macos",
      "mesh-generation",
      "metal",
      "mlx",
      "on-device-ai",
      "photogrammetry",
      "point-cloud",
      "python",
      "sam-3d",
      "spatial-ai",
      "trellis"
    ],
    "homepage": "https://appautomaton.com/mlx-spatial/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/mlx-spatial/sitemap.xml"
  },
  {
    "repoId": 1197331187,
    "createdAt": "2026-03-31T13:54:27Z",
    "catalogOrder": 12,
    "name": "mlx-speech",
    "description": "Pure-MLX speech synthesis, voice cloning, dialogue, sound-effects, and ASR for Apple Silicon: Fish S2 Pro, VibeVoice, LongCat, MOSS, Step-Audio, Cohere ASR.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "asr",
      "mlx",
      "on-device-ai",
      "speech-recognition",
      "speech-synthesis",
      "text-to-speech",
      "tts",
      "voice-cloning"
    ],
    "homepage": "https://appautomaton.com/mlx-speech/",
    "hasSite": true,
    "lastmod": "2026-09-11",
    "sitemap": "https://appautomaton.com/mlx-speech/sitemap.xml"
  },
  {
    "repoId": 1354987267,
    "createdAt": "2026-09-02T16:28:24Z",
    "catalogOrder": 20,
    "name": "mlx-timesfm",
    "description": "Pure MLX inference for Google TimesFM 3.0 on Apple silicon.",
    "topics": [
      "apple-silicon",
      "forecasting",
      "machine-learning",
      "metal",
      "mlx",
      "on-device-ai",
      "python",
      "time-series",
      "timesfm"
    ],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  },
  {
    "repoId": 1145237178,
    "createdAt": "2026-01-29T15:34:55Z",
    "catalogOrder": 8,
    "name": "openclaw-monorepo",
    "description": "Repo-local OpenClaw workspace with modular JSON5 config, plugins, and Docker sandboxes — runs coding-agent CLIs on desktop or Android Termux.",
    "topics": [
      "agentic-workflows",
      "ai-agents",
      "ai-coding-assistant",
      "cli-tool",
      "monorepo",
      "openclaw",
      "pnpm",
      "termux"
    ],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  },
  {
    "repoId": 1299542971,
    "createdAt": "2026-07-13T17:09:56Z",
    "catalogOrder": 11,
    "name": "pi-arcweld",
    "description": "Pi Arcweld, an auditable local workspace for Pi: pinned upstream source, curated extensions, bounded MCP tooling, and a reproducible external runtime (pi-arcweld)",
    "topics": [
      "agent-extensions",
      "agentic-ai",
      "ai-agent",
      "coding-agent",
      "developer-tools",
      "local-first",
      "mcp",
      "model-context-protocol",
      "pi",
      "pi-agent",
      "reproducible-builds",
      "typescript",
      "vendoring"
    ],
    "homepage": "https://appautomaton.com/pi-arcweld/",
    "hasSite": true,
    "lastmod": "2026-09-11",
    "sitemap": "https://appautomaton.com/pi-arcweld/sitemap.xml"
  },
  {
    "repoId": 1125500272,
    "createdAt": "2025-12-30T20:57:29Z",
    "catalogOrder": 4,
    "name": "playwright-skill",
    "description": "Android-friendly Playwright SKILL for AI agents — Termux launcher patch, headless Chromium, install via git subtree into .codex/skills.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "android",
      "browser-automation",
      "claude-code",
      "claude-skills",
      "codex",
      "git-subtree",
      "headless-chromium",
      "mobile-automation",
      "playwright",
      "termux",
      "web-automation"
    ],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  },
  {
    "repoId": 1351955929,
    "createdAt": "2026-08-31T03:40:15Z",
    "catalogOrder": 6,
    "name": "plexmaton",
    "description": "AI coding in your terminal, with clarity and control. Bring your models and skills, review tool actions, and return to conversations with their history intact.",
    "topics": [],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  },
  {
    "repoId": 1192075944,
    "createdAt": "2026-03-25T21:43:24Z",
    "catalogOrder": 2,
    "name": "presentation",
    "description": "A business question goes in. A consulting-grade deck comes out. Four composable skills for Claude Code and Codex: strategy storyboarding, brand identity, pixel-perfect PDF, native editable PPTX.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "claude-skills",
      "codex",
      "playwright",
      "pptx",
      "presentation",
      "slides"
    ],
    "homepage": "https://appautomaton.com/presentation/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/presentation/sitemap.xml"
  },
  {
    "repoId": 1261660195,
    "createdAt": "2026-06-07T01:43:41Z",
    "catalogOrder": 21,
    "name": "setloom",
    "description": "Taste-first club-music production that automates everything but the judgment. You direct in plain language; the agent writes each track's source, drives the synths, renders, and inspects. You never operate a DAW or plug-in; you make every musical call. Open-source, keyboard-first.",
    "topics": [
      "agentic-ai",
      "ai-agents",
      "ai-music",
      "audio",
      "cli",
      "creative-tools",
      "dj",
      "electronic-music",
      "generative-music",
      "melodic-techno",
      "midi",
      "music-production",
      "python",
      "supercollider",
      "techno"
    ],
    "homepage": "https://appautomaton.com/setloom/",
    "hasSite": true,
    "lastmod": "2026-09-11",
    "sitemap": "https://appautomaton.com/setloom/sitemap.xml"
  },
  {
    "repoId": 1157979774,
    "createdAt": "2026-02-14T15:56:37Z",
    "catalogOrder": 13,
    "name": "tnt-asr",
    "description": "Terminal voice-to-text TUI — Qwen3-ASR-1.7B on the Apple GPU via MLX (mlx-speech). Fully local, no PyTorch, transcribes in ~1s. macOS Apple Silicon.",
    "topics": [
      "apple-silicon",
      "asr",
      "dictation",
      "macos",
      "mlx",
      "on-device-ai",
      "python",
      "qwen",
      "speech-recognition",
      "speech-to-text",
      "terminal",
      "tui",
      "voice-to-text",
      "whisper-alternative"
    ],
    "homepage": "https://appautomaton.com/tnt-asr/",
    "hasSite": true,
    "lastmod": "2026-09-10",
    "sitemap": "https://appautomaton.com/tnt-asr/sitemap.xml"
  },
  {
    "repoId": 1204991462,
    "createdAt": "2026-04-08T14:27:15Z",
    "catalogOrder": 3,
    "name": "webmaton",
    "description": "Portable web-research and browser-automation SKILLs for Claude Code, Codex, and OpenCode — Playwright, Chrome DevTools, nodriver, and HTML-to-Markdown.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "browser-automation",
      "cdp",
      "chrome-devtools-protocol",
      "claude-code",
      "codex",
      "html-to-markdown",
      "nodriver",
      "playwright",
      "web-automation",
      "web-research",
      "web-scraping"
    ],
    "homepage": "",
    "hasSite": false,
    "lastmod": null,
    "sitemap": null
  }
]
