/* Post-build prerender: serve dist/, render the page in headless Chromium,
   and write the fully rendered document back to dist/index.html.

   Crawlers that skip JavaScript then see the complete catalog as real HTML.
   In browsers, React's createRoot().render() simply replaces the prerendered
   tree with the identical live one, so nothing visibly changes.

   The sitemap is then written from the links the page actually rendered.
   A sitemap is a list of addresses worth crawling, and a URL that nothing
   links to is not one, so deriving it here makes the two agree by
   construction instead of by memory. */

import { createServer } from 'node:http'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, extname, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright'

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')
const ORIGIN = 'https://appautomaton.renocrypt.com'

const MIME = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.css': 'text/css',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain',
  '.xml': 'application/xml',
}

const server = createServer((req, res) => {
  const path = req.url === '/' ? '/index.html' : req.url.split('?')[0]
  const file = join(DIST, path)
  if (!existsSync(file)) {
    res.writeHead(404).end()
    return
  }
  res.writeHead(200, { 'content-type': MIME[extname(file)] ?? 'application/octet-stream' })
  res.end(readFileSync(file))
})

await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))
const { port } = server.address()

const browser = await chromium.launch()
const page = await browser.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))

await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'networkidle' })
await page.waitForSelector('.aa-card', { timeout: 15000 })

/* The catalog is the source of truth for how many exhibits exist and for
   when each project's page was last built. Node strips the type annotations,
   so it can be read here directly; if a runtime ever cannot, the floor below
   still catches a real regression and the skipped checks say so out loud
   rather than passing quietly. */
let expectedCards = null
let lastmodByUrl = new Map()
let projectSitemaps = []
try {
  const { catalog, unitCount } = await import('../src/data/catalog.ts')
  const projects = catalog.flatMap((s) => s.items)
  expectedCards = unitCount
  lastmodByUrl = new Map(projects.filter((p) => p.site).map((p) => [p.site, p.lastmod]))
  projectSitemaps = projects.map((p) => p.sitemap).filter(Boolean).sort()
} catch (e) {
  console.warn(`warn: card count, lastmod, and robots.txt not applied (${e.message})`)
}

const cards = await page.locator('.aa-card').count()
if (cards < 20) throw new Error(`expected at least 20 prerendered cards, got ${cards}`)
if (expectedCards !== null && cards !== expectedCards)
  throw new Error(`catalog has ${expectedCards} projects but ${cards} cards rendered`)
if (errors.length) throw new Error(`page errors during prerender: ${errors.join(' | ')}`)

const html = await page.content()
await browser.close()
server.close()

writeFileSync(join(DIST, 'index.html'), `<!doctype html>\n${html.replace(/^<!doctype html>/i, '').trimStart()}`)
console.log(`prerendered dist/index.html with ${cards} catalog cards`)

/* --- Sitemap ------------------------------------------------------------
   Every internal address the rendered page links to, and nothing else.

   No changefreq or priority: Google ignores both. lastmod comes from the
   Last-Modified header the serving host returned when the sync step probed
   each page, so it is the date that page was actually built rather than a
   date this build invented. A lastmod that stops matching reality is worse
   than none, because Google drops the signal instead of the page. Anything
   the sync could not date is listed without one. */

const linked = [
  ...new Set(
    [...html.matchAll(/href="(https:\/\/appautomaton\.renocrypt\.com\/[^"#?]*)"/g)].map(
      (m) => m[1],
    ),
  ),
]
  .filter((u) => u !== `${ORIGIN}/`)
  .sort()

const buildDate = new Date().toISOString().slice(0, 10)
const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/prerender.mjs from the links the home page',
  '     actually renders. Edit src/data/catalog.ts, not this file. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  `  <url><loc>${ORIGIN}/</loc><lastmod>${buildDate}</lastmod></url>`,
  ...linked.map((u) => {
    const lastmod = lastmodByUrl.get(u)
    return `  <url><loc>${u}</loc>${lastmod ? `<lastmod>${lastmod}</lastmod>` : ''}</url>`
  }),
  '</urlset>',
  '',
].join('\n')

writeFileSync(join(DIST, 'sitemap.xml'), sitemap)
console.log(`wrote dist/sitemap.xml with ${linked.length + 1} URLs`)

/* --- robots.txt ---------------------------------------------------------
   One robots.txt governs the whole host, so this is the only place a crawler
   can be told that the projects served from subdirectories keep sitemaps of
   their own. The list is the one the sync step found by asking each address,
   which is what keeps it from describing the site as it stood the last time
   somebody edited this by hand. */

const robots = [
  'User-agent: *',
  'Allow: /',
  '',
  '# Generated by scripts/prerender.mjs. Project sitemaps below were found by',
  '# probing each project page, so a project that grows one is declared here',
  '# on the next build without anyone adding it.',
  `Sitemap: ${ORIGIN}/sitemap.xml`,
  ...projectSitemaps.map((u) => `Sitemap: ${u}`),
  '',
].join('\n')

writeFileSync(join(DIST, 'robots.txt'), robots)
console.log(`wrote dist/robots.txt declaring ${projectSitemaps.length + 1} sitemaps`)

/* A URL in the sitemap that does not resolve is a quality signal spent for
   nothing, so a project page that has been taken down should stop the build
   rather than ship. Anything short of a definitive 404 or 410 is treated as
   a network problem and only warned about: deploys should not hinge on the
   weather. */

const checks = await Promise.all(
  linked.map(async (url) => {
    try {
      const res = await fetch(url, {
        method: 'HEAD',
        redirect: 'manual',
        signal: AbortSignal.timeout(10000),
      })
      return { url, status: res.status }
    } catch (e) {
      return { url, error: String(e) }
    }
  }),
)

const gone = checks.filter((c) => c.status === 404 || c.status === 410)
const moved = checks.filter((c) => c.status >= 300 && c.status < 400)
const unknown = checks.filter((c) => c.error)

for (const c of moved) console.warn(`warn: ${c.url} redirects (${c.status}), link the target directly`)
for (const c of unknown) console.warn(`warn: could not verify ${c.url} (${c.error})`)
if (gone.length)
  throw new Error(
    `sitemap lists pages that no longer exist:\n${gone.map((c) => `  ${c.status} ${c.url}`).join('\n')}`,
  )

console.log(`verified ${checks.length - unknown.length}/${checks.length} project pages`)
