/* Generated by scripts/sync-catalog.mjs. Do not edit.

   What the appautomaton org contained at the last build, and what each project's
   address answered when it was asked. Committed so the diff shows when a
   project's description changed or a page went live, and so the site still
   builds with no network. Run `npm run sync` to refresh. */

export type OrgRepo = {
  name: string
  /** The repository's own one-liner, as GitHub reports it. */
  description: string
  topics: string[]
  /** True when https://appautomaton.renocrypt.com/<name>/ answered 200. */
  hasSite: boolean
  /** The date that page was last built, from its Last-Modified header. */
  lastmod: string | null
}

export const org = "appautomaton"
export const origin = "https://appautomaton.renocrypt.com"

export const repos: OrgRepo[] = [
  {
    "name": "agent-designer",
    "description": "Portable SKILLs workspace for Claude Code, Codex, and Gemini — issue-driven workflows and cross-agent collaboration via bridge scripts with session continuity.",
    "topics": [
      "agent-skills",
      "agentic-workflows",
      "ai-agents",
      "ai-coding-assistant",
      "claude-code",
      "claude-skills",
      "codex",
      "gemini-cli",
      "mcp"
    ],
    "hasSite": true,
    "lastmod": "2026-08-05"
  },
  {
    "name": "automaton",
    "description": "AI coding agent framework — portable, stage-gated harness for Claude Code, Codex, and OpenCode",
    "topics": [
      "agentic-workflow",
      "ai-agents",
      "claude-code",
      "codex",
      "developer-tools",
      "llm",
      "opencode"
    ],
    "hasSite": true,
    "lastmod": "2026-07-28"
  },
  {
    "name": "automux",
    "description": "Multi-agent orchestration through tmux or kitty — run Claude Code, Codex, and Gemini CLI in parallel git worktrees with file-based coordination.",
    "topics": [
      "agent-orchestration",
      "agentic-workflows",
      "ai-agents",
      "claude-code",
      "codex",
      "gemini-cli",
      "git-worktree",
      "multi-agent",
      "npm-package",
      "tmux"
    ],
    "hasSite": false,
    "lastmod": null
  },
  {
    "name": "docker-for-apple-container",
    "description": "Run docker and docker compose on macOS, backed by Apple's native container CLI. No Docker Desktop.",
    "topics": [
      "apple-container",
      "apple-silicon",
      "container-cli",
      "containers",
      "docker",
      "docker-cli-shim",
      "docker-compose",
      "docker-desktop-alternative",
      "docker-shim",
      "macos"
    ],
    "hasSite": true,
    "lastmod": "2026-08-05"
  },
  {
    "name": "document-SKILLs",
    "description": "Claude Code and Codex SKILLs for PDF, Excel, Word, and PowerPoint manipulation — extraction, forms, formulas, tracked changes, adapted from Anthropic skills.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "claude-skills",
      "codex",
      "document-processing",
      "docx",
      "excel",
      "pdf-extraction",
      "pptx"
    ],
    "hasSite": true,
    "lastmod": "2026-07-01"
  },
  {
    "name": "latex-arxiv-SKILL",
    "description": "A highly customizable agentic harness for arXiv-ready ML/AI review papers (and beyond). It drives agentic AI like Codex CLI and Claude Code through a gated LaTeX workflow with verified BibTeX citations.",
    "topics": [
      "academic-writing",
      "agent-skill",
      "agentic",
      "agentic-ai",
      "ai-agents",
      "anthropic",
      "arxiv",
      "bibtex",
      "citations",
      "claude-code",
      "codex",
      "ieeetran",
      "latex",
      "literature-review",
      "llm",
      "openai",
      "paper-generation",
      "research-paper",
      "review-paper",
      "scientific-writing"
    ],
    "hasSite": true,
    "lastmod": "2026-08-05"
  },
  {
    "name": "ltx-video-mlx",
    "description": "LTX-2.3 22B text-to-video and image-to-video generation with synchronized audio on Apple Silicon — 8-bit/4-bit MLX inference plus on-device LoRA fine-tuning.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "diffusion-models",
      "image-to-video",
      "lora",
      "mlx",
      "on-device-ai",
      "text-to-video",
      "video-generation"
    ],
    "hasSite": false,
    "lastmod": null
  },
  {
    "name": "markmaton",
    "description": "Lightweight HTML-to-Markdown parser for AI agent workflows — Python CLI and API around a fast Go engine, available on PyPI.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "cli-tool",
      "firecrawl",
      "golang",
      "html-parser",
      "html-to-markdown",
      "llm",
      "markdown",
      "pypi",
      "python",
      "rag",
      "web-scraping"
    ],
    "hasSite": true,
    "lastmod": "2026-08-09"
  },
  {
    "name": "mlx-atomistic",
    "description": "Apple Silicon-native molecular dynamics and DFT runtime built on MLX and Metal — the GPU on your Mac, no CUDA or cloud.",
    "topics": [
      "apple-silicon",
      "atomistic-simulation",
      "computational-chemistry",
      "density-functional-theory",
      "dft",
      "gpu",
      "materials-science",
      "metal",
      "mlx",
      "molecular-dynamics",
      "molecular-simulation",
      "python",
      "scientific-computing"
    ],
    "hasSite": true,
    "lastmod": "2026-08-10"
  },
  {
    "name": "mlx-cv",
    "description": "MLX-native computer vision for Apple Silicon: open-vocabulary grounding, object detection, depth and camera geometry, segmentation, and video object tracking.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "computer-vision",
      "depth-estimation",
      "image-segmentation",
      "macos",
      "mlx",
      "object-detection",
      "object-tracking",
      "on-device-ai",
      "open-vocabulary-detection",
      "panoptic-segmentation",
      "python",
      "sam3",
      "segment-anything",
      "visual-grounding"
    ],
    "hasSite": true,
    "lastmod": "2026-08-08"
  },
  {
    "name": "mlx-h3",
    "description": "Pure MLX MiniMax-H3 text-to-video-and-audio inference for Apple Silicon.",
    "topics": [
      "apple-silicon",
      "audio-generation",
      "generative-ai",
      "macos",
      "minimax-h3",
      "mlx",
      "text-to-video",
      "video-generation"
    ],
    "hasSite": true,
    "lastmod": "2026-08-05"
  },
  {
    "name": "mlx-spatial",
    "description": "MLX-native 3D and spatial inference for Apple silicon: object reconstruction, image-to-mesh, scene geometry, Gaussian splats, and multi-view bundles.",
    "topics": [
      "3d-generation",
      "3d-reconstruction",
      "apple-silicon",
      "gaussian-splatting",
      "image-to-3d",
      "macos",
      "mesh-generation",
      "metal",
      "mlx",
      "on-device-ai",
      "photogrammetry",
      "point-cloud",
      "python",
      "sam-3d",
      "spatial-ai",
      "trellis"
    ],
    "hasSite": true,
    "lastmod": "2026-08-07"
  },
  {
    "name": "mlx-speech",
    "description": "Pure-MLX speech synthesis, voice cloning, dialogue, sound-effects, and ASR for Apple Silicon: Fish S2 Pro, VibeVoice, LongCat, MOSS, Step-Audio, Cohere ASR.",
    "topics": [
      "apple-mlx",
      "apple-silicon",
      "asr",
      "mlx",
      "on-device-ai",
      "speech-recognition",
      "speech-synthesis",
      "text-to-speech",
      "tts",
      "voice-cloning"
    ],
    "hasSite": true,
    "lastmod": "2026-08-05"
  },
  {
    "name": "openclaw-monorepo",
    "description": "Repo-local OpenClaw workspace with modular JSON5 config, plugins, and Docker sandboxes — runs coding-agent CLIs on desktop or Android Termux.",
    "topics": [
      "agentic-workflows",
      "ai-agents",
      "ai-coding-assistant",
      "cli-tool",
      "monorepo",
      "openclaw",
      "pnpm",
      "termux"
    ],
    "hasSite": false,
    "lastmod": null
  },
  {
    "name": "pi-arcweld",
    "description": "Pi Arcweld, an auditable local workspace for Pi: pinned upstream source, curated extensions, bounded MCP tooling, and a reproducible external runtime (pi-arcweld)",
    "topics": [
      "agent-extensions",
      "agentic-ai",
      "ai-agent",
      "coding-agent",
      "developer-tools",
      "local-first",
      "mcp",
      "model-context-protocol",
      "pi",
      "pi-agent",
      "reproducible-builds",
      "typescript"
    ],
    "hasSite": true,
    "lastmod": "2026-08-10"
  },
  {
    "name": "playwright-skill",
    "description": "Android-friendly Playwright SKILL for AI agents — Termux launcher patch, headless Chromium, install via git subtree into .codex/skills.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "android",
      "browser-automation",
      "claude-code",
      "claude-skills",
      "codex",
      "playwright",
      "termux",
      "web-automation"
    ],
    "hasSite": false,
    "lastmod": null
  },
  {
    "name": "presentation",
    "description": "A business question goes in. A consulting-grade deck comes out. Four composable skills for Claude Code and Codex: strategy storyboarding, brand identity, pixel-perfect PDF, native editable PPTX.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "claude-code",
      "claude-skills",
      "codex",
      "playwright",
      "pptx",
      "presentation",
      "slides"
    ],
    "hasSite": true,
    "lastmod": "2026-07-09"
  },
  {
    "name": "setloom",
    "description": "Taste-first club-music production that automates everything but the judgment. You direct in plain language; the agent writes each track's source, drives the synths, renders, and inspects. You never operate a DAW or plug-in; you make every musical call. Open-source, keyboard-first.",
    "topics": [
      "agentic-ai",
      "ai-agents",
      "ai-music",
      "audio",
      "cli",
      "creative-tools",
      "dj",
      "electronic-music",
      "generative-music",
      "melodic-techno",
      "midi",
      "music-production",
      "python",
      "supercollider",
      "techno"
    ],
    "hasSite": true,
    "lastmod": "2026-06-20"
  },
  {
    "name": "tnt-asr",
    "description": "Terminal voice-to-text TUI — Qwen3-ASR-1.7B on the Apple GPU via MLX (mlx-speech). Fully local, no PyTorch, transcribes in ~1s. macOS Apple Silicon.",
    "topics": [
      "apple-silicon",
      "asr",
      "dictation",
      "macos",
      "mlx",
      "on-device-ai",
      "python",
      "qwen",
      "speech-recognition",
      "speech-to-text",
      "terminal",
      "tui",
      "voice-to-text",
      "whisper-alternative"
    ],
    "hasSite": true,
    "lastmod": "2026-06-24"
  },
  {
    "name": "webmaton",
    "description": "Portable web-research and browser-automation SKILLs for Claude Code, Codex, and OpenCode — Playwright, Chrome DevTools, nodriver, and HTML-to-Markdown.",
    "topics": [
      "agent-skills",
      "ai-agents",
      "browser-automation",
      "claude-code",
      "codex",
      "html-to-markdown",
      "playwright",
      "web-automation",
      "web-scraping"
    ],
    "hasSite": false,
    "lastmod": null
  }
]
